<template>
  <Modal 
    :showModal="showModal"
    :carouselLength="3"
    @updateCurrentSlide="updateCurrentSlide($event)"
    @closeModal="$emit('closeModal')"
  >
    <template v-slot:title>
      {{ projectTitle }}
    </template>
    <template v-slot:carousel-slides>
      <li v-if="showModal && currentSlide === 0" class="carousel-slide">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/i0hMaRpgEnk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
      </li>
      <li v-if="showModal && currentSlide === 1" class="carousel-slide">
        <img src="@/assets/imgs/project3/ss1.png"/>
      </li>
      <li v-if="showModal && currentSlide === 2" class="carousel-slide">
        <img src="@/assets/imgs/project3/ss2.png"/>
      </li>
    </template>
    <template v-slot:content>
      {{ displayKeys.content }}
    </template>
    <template v-slot:tech-list>
      <div class="tech-item">    
        <img class="tech-icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg" />          
        <p>C#</p>
      </div>
      <div class="tech-item"> 
        <img class="tech-icon" src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/unity/unity-original.svg" />          
        <p>Unity</p>
      </div>
    </template>
    <template v-slot:about-dev>
      {{ displayKeys.aboutDev }}
    </template>
    <template v-slot:src-ref>
      <a href="https://github.com/chul39/rhythm-runner">https://github.com/chul39/rhythm-runner</a>
    </template>
  </Modal>
</template>

<script>
import { ref, inject, computed } from 'vue'
import Modal from "@/components/Modal.vue"
export default {
  name: "Project3",
  props: {
    projectTitle: String,
    showModal: Boolean
  },
  components: {
    Modal
  },
  setup() {

    const store = inject('store')

    const keys = {
      "EN": {
        content: "A game where players can import external music files into the game and let it generate game stages automatically based on them. The game requires the player to avoid getting hit by the obstacles while collecting the items which will be placed according to the beat of the imported song. The game level is generated by sampling the audio to get its spectrum data and then the pattern is determined by the frequency level of the audio wave.",
        aboutDev: "During my last year in university, I thought that it would be fun to play a runner game while listening to my favorite songs so I created this game as my senior project. From this project, I’ve learnt many things such as Unity’s audio system, resources loading on runtime, and how to handle data between scenes by using singleton."
      },
      "JP": {
        content: "プレイヤーは音楽ファイルをゲームにインポートしてそのファイルに基づいて自動的にゲームレベルが生成されます。ゲームプレイは障害物をかわしながら音楽のビートに合わせて配置されたアイテムを集めていきます。ゲームレベルを生成するには音楽ファイルからスペクトルデータを取得して音波の周波数によってステージのパターンを決めています。",
        aboutDev: "大学時代に好きな曲を聴きながらランナーゲームをやるのは楽しそうと思って卒業制作としてこのゲームを作っていました。このプロジェクトのおかけでUnityのAudioSystemをよく勉強しました。それ以上に、プレイ中にリソースロードする方法やSingletonを使ってシーンをまたいで値を保持する方法などの知識を得ました。",
      }
    }

    const displayKeys = computed(() => {
      return keys[store.state.currentLanguage]
    })

    const currentSlide = ref(0)
    
    const updateCurrentSlide = (value) => {
      currentSlide.value = value
    }

    return { store, displayKeys, updateCurrentSlide, currentSlide }

  }
}
</script>

<style>

</style>